server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5  # 5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10  # 10秒不发送就过期
mybatis:
  type-aliases-package: com.leyou.item.pojo



