server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 172.20.10.14
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 172.20.10.14

leyou:
  sms:
    accessKeyId:                  #你自己的accessKeyId
    accessKeySecret:              #你自己的秘钥
    signName:                     #签名名称
    verifyCodeTemplate:           #模板名称